"""Validate public release facts, README references and safety boundaries.

This is deliberately deterministic: it never calls a model, Docker, GitHub or a
business API.  It checks that the public surface agrees with the checked-in
facts source and that ignored local evidence cannot accidentally be committed.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FACTS_PATH = ROOT / "docs" / "evidence" / "current-release-facts.json"
README_PATH = ROOT / "README.md"
HISTORY_MARKER = "## 历史审计记录"


def fail(message: str) -> None:
    raise SystemExit(f"public_release_validation FAILED: {message}")


def require(condition: bool, message: str) -> None:
    if not condition:
        fail(message)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def git(*args: str) -> str:
    result = subprocess.run(["git", *args], cwd=ROOT, text=True, capture_output=True)
    if result.returncode != 0:
        fail(f"git {' '.join(args)} exited {result.returncode}: {result.stderr.strip()}")
    return result.stdout.strip()


def current_section(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    return text.split(HISTORY_MARKER, 1)[0]


def fastapi_report() -> tuple[dict[str, object], Path]:
    """Load the current CI sidecar, never a historical hard-coded count."""

    candidates: list[Path] = []
    configured = os.getenv("MALL_FASTAPI_REPORT")
    if configured:
        candidates.append((ROOT / configured).resolve() if not Path(configured).is_absolute() else Path(configured))
    candidates.extend(
        [
            ROOT / "mall-ai-service" / "ci-evidence" / "v3-fastapi-report.json",
            ROOT / "mall-ai-service" / "v3-fastapi-report.json",
        ]
    )
    for path in candidates:
        if path.is_file():
            try:
                value = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError) as exc:
                fail(f"FastAPI report cannot be parsed: {exc}")
            if isinstance(value, dict):
                return value, path
    fail("current FastAPI machine-readable report is missing")


def verify_fastapi_report(facts: dict[str, object]) -> dict[str, object]:
    report, path = fastapi_report()
    require(report.get("schemaVersion") == "mall-fastapi-test-report.v1", "FastAPI report schema mismatch")
    head = git("rev-parse", "HEAD")
    report_commit = report.get("repositoryCommit")
    require(isinstance(report_commit, str) and re.fullmatch(r"[0-9a-f]{40}", report_commit) is not None, "FastAPI report repositoryCommit is invalid")
    # The report is generated by the Python gate before the evidence sidecar
    # itself is committed.  Bind the executable runtime exactly through
    # runtimeCommit, and require the report's repository commit to be an
    # ancestor of the evidence commit rather than trusting a historical count.
    ancestor = subprocess.run(["git", "merge-base", "--is-ancestor", report_commit, head], cwd=ROOT)
    require(ancestor.returncode == 0, "FastAPI report is not from the current repository history")
    require(report.get("runtimeCommit") == facts.get("runtimeCommit"), "FastAPI report runtimeCommit mismatch")
    for key in ("passed", "failures", "errors", "skipped", "semanticReportSha256", "junitSha256"):
        require(key in report, f"FastAPI report missing {key}")
    fastapi = facts["tests"]["fastapi"]
    failed = int(report.get("failures", 0)) + int(report.get("errors", 0))
    require(fastapi.get("passed") == report.get("passed"), "FastAPI passed count does not match current report")
    require(fastapi.get("failed") == failed, "FastAPI failed count does not match current report")
    require(fastapi.get("skipped", 0) == report.get("skipped"), "FastAPI skipped count does not match current report")
    require(
        fastapi.get("semanticReportSha256") == report.get("semanticReportSha256"),
        "FastAPI semantic report hash does not match current facts",
    )
    junit_configured = os.getenv("MALL_FASTAPI_JUNIT")
    junit_path = Path(junit_configured) if junit_configured else path.with_name("v3-fastapi-junit.xml")
    if not junit_path.is_absolute():
        junit_path = ROOT / junit_path
    require(junit_path.is_file(), "FastAPI JUnit XML is missing")
    require(sha256(junit_path) == report.get("junitSha256"), "FastAPI JUnit hash does not match sidecar report")
    return report


def fastapi_facts_match(fastapi: dict[str, object], report: dict[str, object]) -> bool:
    """Compare facts with the generated JUnit sidecar without a fixed total."""

    return (
        fastapi.get("passed") == report.get("passed")
        and fastapi.get("failed") == int(report.get("failures", 0)) + int(report.get("errors", 0))
    )


def main() -> int:
    require(FACTS_PATH.is_file(), "current-release-facts.json is missing")
    try:
        facts = json.loads(FACTS_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"facts cannot be parsed: {exc}")

    readme = README_PATH.read_text(encoding="utf-8")
    main_eval = facts["mainEvaluation"]
    supplemental = facts["supplementalEvaluation"]
    tests = facts["tests"]
    field = tests["fieldAcceptance"]
    ci = facts["ci"]
    release_status = facts.get("releaseStatus", "COMPLETE")
    fastapi_report_value = verify_fastapi_report(facts)

    for key in ("schemaVersion", "runtimeCommit", "evidenceCommit", "publicClaims", "prohibitedClaims", "upstreamBoundary"):
        require(key in facts, f"facts missing {key}")
    require(re.fullmatch(r"[0-9a-f]{40}", facts["runtimeCommit"]) is not None, "runtimeCommit must be a full SHA")
    require(
        release_status in {"COMPLETE", "NOT_COMPLETE", "IMPLEMENTATION_READY_FOR_FINAL_VALIDATION"},
        "releaseStatus must be explicit",
    )
    require(supplemental["independentBlindSet"] is False, "supplemental set must not be declared blind")
    if release_status == "COMPLETE":
        require(main_eval["passed"] == main_eval["executed"] == 72, "main evaluation facts mismatch")
        require(supplemental["passed"] == supplemental["executed"] == 36, "supplemental evaluation facts mismatch")
        # The current JUnit sidecar is the authority for this count.  A test
        # suite legitimately grows; release validation must reject a stale
        # facts file, not require a source-code edit for a new test total.
        require(fastapi_facts_match(tests["fastapi"], fastapi_report_value), "FastAPI facts mismatch")
        require(field["total"] == "122/122" and field["failed"] == field["environmentBlocked"] == 0, "field facts mismatch")
    else:
        current = facts.get("currentVerification", {})
        # Runtime identity is distinct from the Git worktree that produced a
        # report.  Evidence-only changes may be uncommitted when validation
        # runs; retain both identities instead of relabelling the worktree as
        # the frozen container runtime.
        current_runtime = current.get("runtimeCommit", current.get("commit"))
        require(current_runtime == facts["runtimeCommit"], "current verification must bind runtimeCommit")
        require(current.get("fastapi", {}).get("passed") == tests["fastapi"]["passed"], "current FastAPI facts mismatch")
        require(current.get("fastapi", {}).get("failed") == tests["fastapi"]["failed"], "current FastAPI failure count mismatch")
        require(current.get("deterministic", {}).get("manifest") == "478/478", "current deterministic facts mismatch")
        deepseek_status = current.get("deepseek", {}).get("status")
        require(deepseek_status in {"environment_blocked", "passed", "failed", "not_run_by_design"}, "DeepSeek status must be explicit")
        if deepseek_status == "not_run_by_design":
            require(current.get("deepseek", {}).get("batchStatus") == "not_run", "DeepSeek not-run status mismatch")
            require(current.get("deepseek", {}).get("calls") == 0, "DeepSeek not-run calls mismatch")
        elif deepseek_status == "environment_blocked":
            require(current.get("deepseek", {}).get("httpStatus") in {401, 402, 403}, "DeepSeek provider blocker status missing")
        elif deepseek_status == "passed":
            require(current.get("deepseek", {}).get("model") == "deepseek-flash", "current DeepSeek model mismatch")
            require(current.get("deepseek", {}).get("batchStatus") == "passed", "current DeepSeek batch status mismatch")
        else:
            require(current.get("deepseek", {}).get("model") == "deepseek-flash", "current DeepSeek model mismatch")
            require(current.get("deepseek", {}).get("batchStatus") == "failed", "current DeepSeek failure status mismatch")
            require(current.get("deepseek", {}).get("calls", 0) > 0, "failed DeepSeek batch must record calls")
            require(current.get("deepseek", {}).get("tokens", 0) > 0, "failed DeepSeek batch must record tokens")
            require(bool(current.get("deepseek", {}).get("releaseId")), "failed DeepSeek batch must record releaseId")
            require(bool(current.get("deepseek", {}).get("batchId")), "failed DeepSeek batch must record batchId")
            require(current.get("deepseek", {}).get("ledgerReconciled") is True, "failed DeepSeek batch ledger must reconcile")
        showcase_status = current.get("showcase", {}).get("status")
        require(showcase_status in {"environment_blocked", "passed", "failed", "not_executed"}, "showcase status must be explicit")
        require(
            all(item.get("status") in {"environment_blocked", "passed", "failed", "not_executed"} for item in current["showcase"].get("scenarios", [])),
            "showcase scenario status mismatch",
        )
        if release_status == "IMPLEMENTATION_READY_FOR_FINAL_VALIDATION":
            readiness = facts.get("v3_0_3OfflineReadiness", {})
            require(readiness.get("status") == release_status, "v3.0.3 readiness status mismatch")
            require(readiness.get("currentCandidateProviderRequests") == 0, "current candidate must not inherit historical provider calls")
            require(readiness.get("currentLiveEvaluation") == "not_run_for_current_runtime", "current live evaluation state mismatch")
            require(readiness.get("historicalInvalidatedRun") is True, "historical invalidated run must remain recorded")
        elif deepseek_status == "failed":
            require(facts.get("claims", {}).get("releaseQualified") is False, "failed live batch cannot qualify release")
            require(current.get("showcase", {}).get("status") == "failed", "failed live batch must fail showcase")
    require(tests["java"]["portalCore"] == "12/12", "Java portal core fact mismatch")
    require(tests["java"]["portalCompatibility"] == "2/2", "Java portal compatibility fact mismatch")
    require(tests["java"]["admin"] == "6/6", "Java admin fact mismatch")
    require(tests["java"]["springContext"] == "1/1", "Spring context fact mismatch")
    # Preserve the historical suite shape for audit, while allowing a
    # NOT_COMPLETE release to mark the old field report stale after a runtime
    # change. The stale 122/122 is never treated as a current gate here.
    require(field["total"] == "122/122", "field facts must preserve the historical suite shape")

    forbidden_phrases = (
        "## 评测发现与改进方向",
        "portal `14/14`",
        "portal 14/14",
        "独立合成 holdout",
        "独立合成 Holdout",
        "独立 12 Case",
        "独立12 Case",
        "各 `52/52`",
        "各52/52",
        "52/52 全部通过",
    )
    for phrase in forbidden_phrases:
        require(phrase not in readme, f"README contains forbidden public wording: {phrase}")
    if release_status == "NOT_COMPLETE":
        required_fragments = (
            "DeepSeek",
            f"{tests['fastapi']['passed']} passed",
            "portal 核心 `12/12`",
            "admin `6/6`",
            "Spring context `1/1`",
            "478/478",
        )
        for fragment in required_fragments:
            require(fragment in readme, f"README missing fact fragment: {fragment}")
        require("不是独立盲测集" in readme, "README must disclose supplemental-set boundary")
    elif release_status == "IMPLEMENTATION_READY_FOR_FINAL_VALIDATION":
        require("PORTFOLIO_RELEASE_COMPLETE" not in readme, "README must not predeclare release completion")
    require(
        re.search(r"52/52.{0,20}(准确率|全部通过)|(?:准确率|全部通过).{0,20}52/52", readme) is None,
        "README must not present retrieval as a 52/52 accuracy/pass claim",
    )

    # Validate local Markdown links and image references used by the README.
    references = re.findall(r"!\[[^]]*\]\(([^)]+)\)|\[[^]]+\]\(([^)]+)\)", readme)
    image_hashes: set[str] = set()
    local_images: list[Path] = []
    for image_ref, link_ref in references:
        ref = image_ref or link_ref
        if not ref or "://" in ref or ref.startswith("#"):
            continue
        path = (ROOT / ref.split("#", 1)[0]).resolve()
        require(path.is_file(), f"README reference missing: {ref}")
        if path.suffix.lower() in {".png", ".jpg", ".jpeg", ".gif", ".webp"}:
            local_images.append(path)
            digest = sha256(path)
            require(digest not in image_hashes, f"README images have duplicate hash: {ref}")
            image_hashes.add(digest)
    final_gif = ROOT / "docs" / "assets" / "showcase-final" / "main-open-task-closed-loop.gif"
    if release_status == "COMPLETE":
        require(final_gif.is_file(), "final showcase GIF is missing")
        require(final_gif.stat().st_size <= 3 * 1024 * 1024, "final showcase GIF exceeds 3 MB")
    else:
        require((ROOT / "scripts" / "Capture-PublicShowcase.ps1").is_file(), "tracked showcase capture entry is missing")

    ignored = subprocess.run(["git", "check-ignore", "-q", "mall-ai-service/tmp/"], cwd=ROOT)
    require(ignored.returncode == 0, "mall-ai-service/tmp/ is not ignored")
    tracked = git("ls-files").splitlines()
    # Names such as ``.env.example`` and Java DTOs containing ``Password`` or
    # ``Session`` are intentional source/templates.  Reject only actual local
    # env files and private-key/credential artifacts.
    risky = [
        p for p in tracked
        if re.search(r"(^|/)\.env$|(^|/)\.env\.(?!example$)|(^|/)(id_rsa|credentials?|.*\.(pem|key|p12))$", p, re.I)
    ]
    require(not risky, f"sensitive-looking tracked paths found: {', '.join(risky)}")
    require(not any("mall-ai-service/tmp/" in p for p in tracked), "raw tmp reports are tracked")

    head = git("rev-parse", "HEAD")
    runtime = facts["runtimeCommit"]
    ancestor = subprocess.run(["git", "merge-base", "--is-ancestor", runtime, head], cwd=ROOT)
    require(ancestor.returncode == 0, "runtimeCommit is not an ancestor of HEAD")
    post_runtime = git("diff", "--name-only", f"{runtime}..HEAD").splitlines()
    runtime_prefixes = ("mall-ai-service/app/", "mall2/", "mall-ai-web/src/", "evals/", "mall2/document/sql/migrations/")
    # The v3.0.4 freeze deliberately keeps the contract-replay evaluator and
    # its immutable case-set fixture outside the deployed Runtime surface.
    # They were added after the last field run to make replay provenance
    # explicit; allowing only these two exact paths prevents arbitrary
    # post-freeze production changes from being hidden as evidence updates.
    evaluation_only_post_freeze = {
        "mall-ai-service/app/runtime/contract_replay_evaluation.py",
        "evals/live_model_agent_contract_replay.v1.json",
    }
    changed_runtime = [
        p for p in post_runtime
        if p.startswith(runtime_prefixes) and p not in evaluation_only_post_freeze
    ]
    require(not changed_runtime, f"runtime files changed after evaluated commit: {', '.join(changed_runtime)}")

    # Current sections of evidence docs must match; old sections remain allowed only
    # below the explicit historical marker.
    current_docs = [
        ROOT / "docs" / "evidence" / "release-gate-summary.md",
        ROOT / "docs" / "evidence" / "resume-fact-pack.md",
        ROOT / "docs" / "final-handoff" / "00-final-status.md",
        ROOT / "docs" / "final-handoff" / "03-test-evaluation-evidence.md",
        ROOT / "docs" / "PUBLIC_RELEASE_RECORD.md",
    ]
    for path in current_docs:
        section = current_section(path)
        if release_status == "COMPLETE":
            require("72/72" in section and "36/36" in section and "122/122" in section, f"current claims incomplete in {path}")
            require("14/14" not in section and "holdout" not in section.lower(), f"stale wording remains in current document {path}")
            require(str(tests["fastapi"]["passed"]) in section, f"current FastAPI count is missing in {path}")
        else:
            require(release_status in section, f"current release status missing in {path}")
            require(
                "environment_blocked" in section
                or "Batch 2" in section
                or "not_executed" in section
                or "not_run_by_design" in section,
                f"current incomplete boundary missing in {path}",
            )
            require(str(tests["fastapi"]["passed"]) in section, f"current FastAPI count is missing in {path}")
    require(ci["status"] in {"pending_remote_final_sha", "passed", "failed_current_sha"}, "CI status must be explicit")

    print(
        "public_release_validation PASSED "
        f"head={head[:12]} runtime={runtime[:12]} "
        f"status={release_status} current_fastapi={fastapi_report_value.get('passed')} "
        f"historical_main={main_eval['passed']}/{main_eval['executed']} historical_field={field['total']} "
        f"images={len(local_images)} ci={ci['status']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
